# Informações do Projeto
site_name: wGalletiDocs
site_description: 'William Galleti Docs'
site_author: 'William Galleti'
site_url: 'http://wGalleti.io/docs'

# Documentos e Temas
docs_dir: 'docs'
theme : 'material'

# Copyright
copyright: '© 2017 wGalleti'

# Opções
extra:
  palette:
    primary: 'indigo'
    accent: 'light blue'
  font:
    text: 'Ubuntu'
    code: 'Ubuntu Mono'
  feature:
    tabs: true
  social:
    - type: 'github'
      link: 'https://github.com/wGalleti'
    - type: 'twitter'
      link: 'https://twitter.com/wGalleti'
    - type: 'linkedin'
      link: 'https://www.linkedin.com/in/william-galleti-6b97a833/'

# Extensions
markdown_extensions:
  - admonition
  - codehilite(guess_lang=false,linenums=true)
  - toc(permalink=true)
  - footnotes
  - meta
  - pymdownx.arithmatex
  - pymdownx.betterem(smart_enable=all)
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.emoji:
      emoji_generator: !!python/name:pymdownx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist(custom_checkbox=true)
  - pymdownx.tilde

# Paginas
pages:
  - 'Home': 'index.md'
  # - 'Sobre' : 'sobre.md'
  # - 'Estudos':
  #   - 'Python': 'estudos/python.md'
  #   - 'Django': 'estudos/django.md'
  #   - 'AngularJS': 'estudos/angularjs.md'
  #   - 'Angular': 'estudos/angular.md'
  - 'Tutoriais':
    - 'Django':
      - 'Server':
        - 'Ubuntu Apache': 'tutoriais/django/server/ubuntu_apache.md'
      - 'Projeto Heroku': 'tutoriais/django/heroku.md'
      - 'Rest Framework': 'tutoriais/django/rest_framework.md'
      # - 'JET Admin': 'tutoriais/django/jet_admin.md'
    # - 'AngularJS': 
    #   - 'Snippets Sublime': 'tutoriais/angularjs/snippets_sublime.md'
    #   - 'Snippets VSCode': 'tutoriais/angularjs/snippets_vscode.md'
    #   - 'UI - Router': 'tutoriais/angularjs/ui_router.md'
    # - 'Oracle':
    #   - 'Backup': 'tutoriais/oracle/backup.md'
    #   - 'Import': 'tutoriais/oracle/import.md'
    #   - 'Connect': 'tutoriais/oracle/connect.md'

